### ISSUE TITLE
Error on updating feed.

### ISSUE THREAD

**Issue by Carlingr** [edthedev/podcast-grabber#1]
returns 

    Traceback (most recent call last):
      File "./podgrab.py", line 648, in <module>
        main(sys.argv[1:])
      File "./podgrab.py", line 195, in main
        message = iterate_feed(data, mode, download_directory, todays_date, cursor, connection, 
    feed_url)
      File "./podgrab.py", line 334, in iterate_feed
        num_podcasts = iterate_channel(channel, today, mode, cur, conn, feed, channel_directory)
      File "./podgrab.py", line 564, in iterate_channel
        size = size + int(item_size)
    ValueError: invalid literal for int() with base 10: ''

in command line. Does not appear to happen on any particular subscription.

**Comment by edthedev** [comment]
This app was written many years ago for Python 2.3. Looks like you are trying to run it with modern Python 3+.

It will need a lot of small updates to be compatible.

I no longer use or maintain this package, but pull requests will be reviewed and merged in a timely manner of someone wants to update it.
